services:
  web:
    build: ./django
    image: aoieu
    env_file:
      - ./.env_aoieu
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/app/
    ports:
      - 8000:8000
    depends_on:
      - migration
      - db
  
  migration:
    image: aoieu
    env_file:
      - ./.env_aoieu
    command: bash -c "python manage.py flush --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser --noinput"
    volumes:
      - ./django:/app/
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - ./.env_aoieu
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: