services:
  web1:
    build: .
    image: aoieu
    env_file:
      - ./.env_aoieu
    command: gunicorn kadmin.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - .:/app/
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - 8001
    depends_on:
      - migration
      - db
  web2:
    build: .
    image: aoieu
    env_file:
      - ./.env_aoieu
    command: gunicorn kadmin.wsgi:application --bind 0.0.0.0:8002
    volumes:
      - .:/app/
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - 8002
    depends_on:
      - migration
      - db
  
  migration:
    image: aoieu
    env_file:
      - ./.env_aoieu
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser --noinput && python manage.py collectstatic --noinput"
    volumes:
      - .:/app/
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - ./.env_aoieu
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx1:
    build: ./nginx1
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - 81
    depends_on:
      - web1

  nginx2:
    build: ./nginx2
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - 82
    depends_on:
      - web2

  haproxy:
    build: ./haproxy
    ports:
     - '80:80'
     - '443:443'
    depends_on:
      - nginx1
      - nginx2


volumes:
  postgres_data:
  static_volume:
  media_volume: