# Generated by Django 4.2.6 on 2023-10-25 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoieu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxy',
            name='name',
            field=models.CharField(db_index=True, max_length=400, unique=True, validators=[django.core.validators.RegexValidator('^[a-z+]', 'Only alpha characters.')]),
        ),
        migrations.AlterField(
            model_name='moon',
            name='name',
            field=models.CharField(db_index=True, max_length=400, unique=True, validators=[django.core.validators.RegexValidator('^[a-z+]', 'Only alpha characters.')]),
        ),
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(db_index=True, max_length=400, unique=True, validators=[django.core.validators.RegexValidator('^[a-z+]', 'Only alpha characters.')]),
        ),
        migrations.AlterField(
            model_name='star',
            name='name',
            field=models.CharField(db_index=True, max_length=400, unique=True, validators=[django.core.validators.RegexValidator('^[a-z+]', 'Only alpha characters.')]),
        ),
    ]
