# Generated by Django 4.2.7 on 2023-11-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoieu', '0003_alter_galaxy_name_alter_moon_name_alter_planet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxy',
            name='image',
            field=models.ImageField(blank=True, upload_to='galaxies'),
        ),
        migrations.AlterField(
            model_name='moon',
            name='image',
            field=models.ImageField(blank=True, upload_to='moons'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='image',
            field=models.ImageField(blank=True, upload_to='planets'),
        ),
        migrations.AlterField(
            model_name='star',
            name='image',
            field=models.ImageField(blank=True, upload_to='stars'),
        ),
    ]
